server:
  port: 8082

spring:
  application:
    name: eApiGateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: test
          uri: lb://eClient
          predicates:
            - Path=/api/test





eureka:
  client:
    service-url:
      defaultZone:
        http://localhost:8081/eureka

